// resources/js/Pages/Inventory/Transfers/Create.vue
<!-- ponytail: New Transfer (§3F) — always starts as a draft; posting is a separate step. -->
<script setup lang="ts">
import { useForm, Link } from '@inertiajs/vue3'
import { computed } from 'vue'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import Panel from '@/Components/cards/Panel.vue'
import FormInput from '@/Components/forms/FormInput.vue'
import FormSelect from '@/Components/forms/FormSelect.vue'
import TransferLineListInput, { type TransferLineRow } from '@/Components/inventory/TransferLineListInput.vue'
import InventorySubNav from '@/Components/inventory/InventorySubNav.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'

const props = defineProps<{
  warehouses: Array<{ id: number; name: string }>
  uoms: Array<{ id: number; code: string; name: string }>
  locations: Array<{ id: number; warehouse_id: number; code: string }>
  productTracking: Record<number, string>
}>()

const form = useForm({
  source_warehouse_id: null as number | null,
  source_location_id: null as number | null,
  destination_warehouse_id: null as number | null,
  destination_location_id: null as number | null,
  transfer_date: new Date().toISOString().slice(0, 10),
  lines: [] as TransferLineRow[],
})

const sourceLocationOptions = computed(() =>
  props.locations.filter((l) => Number(l.warehouse_id) === Number(form.source_warehouse_id)).map((l) => ({ label: l.code, value: l.id })),
)
const destinationLocationOptions = computed(() =>
  props.locations.filter((l) => Number(l.warehouse_id) === Number(form.destination_warehouse_id)).map((l) => ({ label: l.code, value: l.id })),
)

const submit = () => form.post(route('inventory.transfers.store'))
</script>

<template>
  <AppLayout>
    <PageHeader title="New Transfer" description="Saved as a draft — post it once the lines are correct." />

    <InventorySubNav active="transfers" class="mt-6" />

    <Panel class="mt-6 max-w-4xl">
      <form class="space-y-4" @submit.prevent="submit">
        <FormInput v-model="form.transfer_date" name="transfer_date" type="date" label="Transfer date" :error="form.errors.transfer_date" required />

        <div class="grid grid-cols-2 gap-4 rounded-md border border-border p-3">
          <div class="space-y-4">
            <p class="text-xs font-semibold uppercase tracking-wide text-ink-600">Source</p>
            <FormSelect
              v-model="form.source_warehouse_id"
              name="source_warehouse_id"
              label="Warehouse"
              placeholder="Select a warehouse…"
              :options="warehouses.map((w) => ({ label: w.name, value: w.id }))"
              :error="form.errors.source_warehouse_id"
              required
            />
            <FormSelect
              v-model="form.source_location_id"
              name="source_location_id"
              label="Location"
              placeholder="Choose a bin…"
              :options="sourceLocationOptions"
              :error="form.errors.source_location_id"
              :disabled="!form.source_warehouse_id"
              required
            />
          </div>
          <div class="space-y-4">
            <p class="text-xs font-semibold uppercase tracking-wide text-ink-600">Destination</p>
            <FormSelect
              v-model="form.destination_warehouse_id"
              name="destination_warehouse_id"
              label="Warehouse"
              placeholder="Select a warehouse…"
              :options="warehouses.map((w) => ({ label: w.name, value: w.id }))"
              :error="form.errors.destination_warehouse_id"
              required
            />
            <FormSelect
              v-model="form.destination_location_id"
              name="destination_location_id"
              label="Location"
              placeholder="Choose a bin…"
              :options="destinationLocationOptions"
              :error="form.errors.destination_location_id"
              :disabled="!form.destination_warehouse_id"
              required
            />
          </div>
        </div>

        <TransferLineListInput v-model="form.lines" :uoms="uoms" :product-tracking="productTracking" />
        <p v-if="form.errors.lines" class="text-sm text-signal-danger">{{ form.errors.lines }}</p>

        <div class="flex items-center justify-end gap-3 border-t border-border pt-4">
          <Link
            :href="route('inventory.transfers.index')"
            class="inline-flex items-center justify-center rounded-sm border border-border bg-surface-0 px-3 py-2 text-sm font-semibold text-ink-900 shadow-sm transition hover:bg-surface-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
          >
            Cancel
          </Link>
          <PrimaryButton type="submit" :disabled="form.processing">Save draft</PrimaryButton>
        </div>
      </form>
    </Panel>
  </AppLayout>
</template>

// next-fe/src/app/inventory/create/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import PageHeader from "@/components/layout/PageHeader";
import FormInput from "@/components/forms/FormInput";
import FormSelect from "@/components/forms/FormSelect";
import { getCategories, saveItem, Category } from "@/lib/storage";

export default function CreateItemPage() {
  const router = useRouter();
  const [categories, setCategories] = useState<Category[]>([]);

  // Form Fields State
  const [code, setCode] = useState("");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [stock, setStock] = useState("0");
  const [minimumStock, setMinimumStock] = useState("0");
  const [unit, setUnit] = useState("");
  const [status, setStatus] = useState("active");

  // Error States
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    setCategories(getCategories());
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrors({});

    // Validate
    const newErrors: Record<string, string> = {};
    if (!code.trim()) newErrors.code = "Item code is required.";
    if (!name.trim()) newErrors.name = "Item name is required.";
    if (!categoryId) newErrors.categoryId = "Category is required.";
    if (!unit.trim()) newErrors.unit = "Unit of measurement is required.";
    if (isNaN(Number(stock)) || Number(stock) < 0) {
      newErrors.stock = "Stock must be a positive number.";
    }
    if (isNaN(Number(minimumStock)) || Number(minimumStock) < 0) {
      newErrors.minimumStock = "Minimum stock must be a positive number.";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    setIsSubmitting(true);

    try {
      saveItem({
        code: code.trim().toUpperCase(),
        name: name.trim(),
        description: description.trim(),
        inventory_category_id: Number(categoryId),
        stock: Number(stock),
        minimum_stock: Number(minimumStock),
        unit: unit.trim(),
        status: status as "active" | "inactive" | "archived",
      });

      router.push("/inventory");
    } catch (err) {
      console.error(err);
      setIsSubmitting(false);
    }
  };

  const categoryOptions = categories.map((c) => ({
    label: c.name,
    value: c.id,
  }));

  return (
    <AppLayout>
      <PageHeader
        title="Create Inventory Item"
        description="Add a new item to stock tracking."
      />

      <div className="mt-6 max-w-2xl rounded-xl border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm">
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput
              name="code"
              label="Item Code"
              placeholder="e.g. RAW-001"
              value={code}
              onChange={setCode}
              error={errors.code}
              required
            />

            <FormInput
              name="name"
              label="Item Name"
              placeholder="e.g. Steel Plate"
              value={name}
              onChange={setName}
              error={errors.name}
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormSelect
              name="inventory_category_id"
              label="Category"
              placeholder="Select category"
              value={categoryId}
              onChange={setCategoryId}
              options={categoryOptions}
              error={errors.categoryId}
              required
            />

            <FormInput
              name="unit"
              label="Unit of Measurement"
              placeholder="e.g. pcs, box, kg"
              value={unit}
              onChange={setUnit}
              error={errors.unit}
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput
              name="stock"
              label="Current Stock"
              type="number"
              value={stock}
              onChange={setStock}
              error={errors.stock}
              required
            />

            <FormInput
              name="minimum_stock"
              label="Minimum Safety Stock"
              type="number"
              value={minimumStock}
              onChange={setMinimumStock}
              error={errors.minimumStock}
              required
            />
          </div>

          <FormSelect
            name="status"
            label="Status"
            placeholder="Select status"
            value={status}
            onChange={setStatus}
            options={[
              { label: "Active", value: "active" },
              { label: "Inactive", value: "inactive" },
              { label: "Archived", value: "archived" },
            ]}
            required
          />

          <div className="space-y-1.5">
            <label
              htmlFor="description"
              className="block text-xs font-semibold text-slate-700 dark:text-slate-350"
            >
              Description
            </label>
            <textarea
              id="description"
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Optional brief description..."
              className="w-full rounded-lg border border-slate-250 dark:border-slate-800 bg-white dark:bg-slate-900 px-3 py-2 text-xs shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 dark:text-slate-200"
            ></textarea>
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
            <Link
              href="/inventory"
              className="text-xs font-bold text-slate-750 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white px-3 py-2"
            >
              Cancel
            </Link>
            <button
              type="submit"
              disabled={isSubmitting}
              className="rounded-xl bg-indigo-650 px-4 py-2 text-xs font-bold text-white shadow-md shadow-indigo-650/10 hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-50 active:scale-[0.98] transition-all"
            >
              {isSubmitting ? "Saving..." : "Save Item"}
            </button>
          </div>
        </form>
      </div>
    </AppLayout>
  );
}
