// next-fe/src/app/inventory/create/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import PageHeader from "@/components/layout/PageHeader";
import FormInput from "@/components/forms/FormInput";
import FormSelect from "@/components/forms/FormSelect";
import { getCategories, saveItem, Category } from "@/lib/storage";

export default function CreateItemPage() {
  const router = useRouter();
  const [categories, setCategories] = useState<Category[]>([]);

  // Form Fields State
  const [code, setCode] = useState("");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [stock, setStock] = useState("0");
  const [minimumStock, setMinimumStock] = useState("0");
  const [unit, setUnit] = useState("");
  const [status, setStatus] = useState("active");

  // Error States
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    setCategories(getCategories());
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrors({});

    // Validate
    const newErrors: Record<string, string> = {};
    if (!code.trim()) newErrors.code = "Item code is required.";
    if (!name.trim()) newErrors.name = "Item name is required.";
    if (!categoryId) newErrors.categoryId = "Category is required.";
    if (!unit.trim()) newErrors.unit = "Unit of measurement is required.";
    if (isNaN(Number(stock)) || Number(stock) < 0) {
      newErrors.stock = "Stock must be a positive number.";
    }
    if (isNaN(Number(minimumStock)) || Number(minimumStock) < 0) {
      newErrors.minimumStock = "Minimum stock must be a positive number.";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    setIsSubmitting(true);

    try {
      saveItem({
        code: code.trim().toUpperCase(),
        name: name.trim(),
        description: description.trim(),
        inventory_category_id: Number(categoryId),
        stock: Number(stock),
        minimum_stock: Number(minimumStock),
        unit: unit.trim(),
        status: status as "active" | "inactive" | "archived",
      });

      router.push("/inventory");
    } catch (err) {
      console.error(err);
      setIsSubmitting(false);
    }
  };

  const categoryOptions = categories.map((c) => ({
    label: c.name,
    value: c.id,
  }));

  return (
    <AppLayout>
      <PageHeader
        title="Create Inventory Item"
        description="Add a new item to stock tracking."
      />

      <div className="mt-6 max-w-2xl rounded-xl border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm">
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput
              name="code"
              label="Item Code"
              placeholder="e.g. RAW-001"
              value={code}
              onChange={setCode}
              error={errors.code}
              required
            />

            <FormInput
              name="name"
              label="Item Name"
              placeholder="e.g. Steel Plate"
              value={name}
              onChange={setName}
              error={errors.name}
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormSelect
              name="inventory_category_id"
              label="Category"
              placeholder="Select category"
              value={categoryId}
              onChange={setCategoryId}
              options={categoryOptions}
              error={errors.categoryId}
              required
            />

            <FormInput
              name="unit"
              label="Unit of Measurement"
              placeholder="e.g. pcs, box, kg"
              value={unit}
              onChange={setUnit}
              error={errors.unit}
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput
              name="stock"
              label="Current Stock"
              type="number"
              value={stock}
              onChange={setStock}
              error={errors.stock}
              required
            />

            <FormInput
              name="minimum_stock"
              label="Minimum Safety Stock"
              type="number"
              value={minimumStock}
              onChange={setMinimumStock}
              error={errors.minimumStock}
              required
            />
          </div>

          <FormSelect
            name="status"
            label="Status"
            placeholder="Select status"
            value={status}
            onChange={setStatus}
            options={[
              { label: "Active", value: "active" },
              { label: "Inactive", value: "inactive" },
              { label: "Archived", value: "archived" },
            ]}
            required
          />

          <div className="space-y-1.5">
            <label
              htmlFor="description"
              className="block text-xs font-semibold text-slate-700 dark:text-slate-350"
            >
              Description
            </label>
            <textarea
              id="description"
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Optional brief description..."
              className="w-full rounded-lg border border-slate-250 dark:border-slate-800 bg-white dark:bg-slate-900 px-3 py-2 text-xs shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 dark:text-slate-200"
            ></textarea>
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
            <Link
              href="/inventory"
              className="text-xs font-bold text-slate-750 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white px-3 py-2"
            >
              Cancel
            </Link>
            <button
              type="submit"
              disabled={isSubmitting}
              className="rounded-xl bg-indigo-650 px-4 py-2 text-xs font-bold text-white shadow-md shadow-indigo-650/10 hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-50 active:scale-[0.98] transition-all"
            >
              {isSubmitting ? "Saving..." : "Save Item"}
            </button>
          </div>
        </form>
      </div>
    </AppLayout>
  );
}

// resources/js/Pages/Legal/Matters/Create.vue
<!-- ponytail: Create matter (§3B) — Panel + Primary/SecondaryButton -->
<script setup lang="ts">
import { useForm, Link } from '@inertiajs/vue3'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import Panel from '@/Components/cards/Panel.vue'
import FormInput from '@/Components/forms/FormInput.vue'
import FormSelect from '@/Components/forms/FormSelect.vue'
import FormAsyncSearchableSelect from '@/Components/forms/FormAsyncSearchableSelect.vue'
import CustomFieldInputs, { type CustomFieldDef } from '@/Components/forms/CustomFieldInputs.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'

const props = defineProps<{
  assignees: Array<{ id: number; name: string }>
  customFields: CustomFieldDef[]
}>()

const customBag: Record<string, string> = {}
for (const f of props.customFields) {
  customBag[f.code] = f.value ?? ''
}

const form = useForm({
  code: '',
  title: '',
  matter_type: '',
  partner_id: null as number | null,
  assigned_to: null as number | null,
  status: 'open',
  opened_at: '',
  target_close_at: '',
  notes: '',
  custom_fields: customBag,
})

const submit = () => form.post(route('legal.matters.store'))
</script>

<template>
  <AppLayout>
    <PageHeader
      title="Open matter"
      description="Register a new client engagement. Leave code blank to allocate from Serials."
    />

    <Panel class="mt-6 max-w-xl">
      <form class="space-y-4" @submit.prevent="submit">
        <FormInput
          v-model="form.code"
          name="code"
          label="Matter code"
          placeholder="Leave blank to auto-generate"
          :error="form.errors.code"
        />
        <FormInput v-model="form.title" name="title" label="Title" :error="form.errors.title" required />
        <FormInput
          v-model="form.matter_type"
          name="matter_type"
          label="Matter type"
          placeholder="e.g. Property Purchase, Company Incorporation"
          :error="form.errors.matter_type"
        />
        <FormAsyncSearchableSelect
          v-model="form.partner_id"
          name="partner_id"
          label="Primary client"
          api-entity="crm_partner"
          placeholder="Search for a contact or company…"
          :error="form.errors.partner_id"
        />
        <FormSelect
          v-model="form.assigned_to"
          name="assigned_to"
          label="Assigned notary/PPAT"
          placeholder="Unassigned"
          :options="assignees.map((a) => ({ label: a.name, value: a.id }))"
          :error="form.errors.assigned_to"
        />
        <FormSelect
          v-model="form.status"
          name="status"
          label="Status"
          :options="[
            { label: 'Open', value: 'open' },
            { label: 'In progress', value: 'in_progress' },
            { label: 'On hold', value: 'on_hold' },
            { label: 'Closed', value: 'closed' },
          ]"
          :error="form.errors.status"
          required
        />
        <div class="grid grid-cols-2 gap-4">
          <FormInput v-model="form.opened_at" name="opened_at" type="date" label="Opened" :error="form.errors.opened_at" />
          <FormInput v-model="form.target_close_at" name="target_close_at" type="date" label="Target close" :error="form.errors.target_close_at" />
        </div>
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-ink-900">Notes</label>
          <textarea
            v-model="form.notes"
            rows="3"
            class="w-full rounded-sm border border-border bg-surface-0 px-3 py-2 text-sm text-ink-900 shadow-sm focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"
          />
        </div>
        <CustomFieldInputs
          v-model="form.custom_fields"
          :fields="customFields"
          :errors="form.errors"
        />
        <div class="flex items-center justify-end gap-3 border-t border-border pt-4">
          <Link
            :href="route('legal.matters.index')"
            class="inline-flex items-center justify-center rounded-sm border border-border bg-surface-0 px-3 py-2 text-sm font-semibold text-ink-900 shadow-sm transition hover:bg-surface-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
          >
            Cancel
          </Link>
          <PrimaryButton type="submit" :disabled="form.processing">Save matter</PrimaryButton>
        </div>
      </form>
    </Panel>
  </AppLayout>
</template>
