// resources/js/Components/layout/PageHeader.vue
<!-- ponytail: Simple PageHeader component with slots for action items -->
<script setup lang="ts">
defineProps<{
  title: string
  description?: string
}>()
</script>

<template>
  <div class="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between border-b border-gray-200 pb-5">
    <div>
      <h1 class="text-2xl font-bold tracking-tight text-gray-900">{{ title }}</h1>
      <p v-if="description" class="text-sm text-gray-500 mt-1">{{ description }}</p>
    </div>
    <div class="flex items-center gap-3 mt-4 sm:mt-0">
      <slot name="actions" />
    </div>
  </div>
</template>

// next-fe/src/components/layout/PageHeader.tsx
import React from "react";

interface PageHeaderProps {
  title: string;
  description?: string;
  children?: React.ReactNode;
}

export default function PageHeader({ title, description, children }: PageHeaderProps) {
  return (
    <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between border-b border-slate-100 dark:border-slate-800 pb-5">
      <div className="space-y-1">
        <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
          {title}
        </h1>
        {description && (
          <p className="text-xs text-slate-500 dark:text-slate-400">
            {description}
          </p>
        )}
      </div>
      {children && (
        <div className="flex items-center gap-3 mt-4 sm:mt-0">
          {children}
        </div>
      )}
    </div>
  );
}
