// resources/js/Pages/CRM/Leads/Edit.vue
<!-- ponytail: Edit Lead (§3D) — form + stage status + Convert/Disqualify actions + activity log -->
<script setup lang="ts">
import { ref } from 'vue'
import { useForm, Link } from '@inertiajs/vue3'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import Panel from '@/Components/cards/Panel.vue'
import FormInput from '@/Components/forms/FormInput.vue'
import FormSelect from '@/Components/forms/FormSelect.vue'
import StatusBadge from '@/Components/feedback/StatusBadge.vue'
import CustomFieldInputs, { type CustomFieldDef } from '@/Components/forms/CustomFieldInputs.vue'
import CrmSubNav from '@/Components/crm/CrmSubNav.vue'
import LeadActivityLog, { type LeadActivityRow } from '@/Components/crm/LeadActivityLog.vue'
import ConvertLeadModal from '@/Components/crm/ConvertLeadModal.vue'
import DisqualifyLeadModal from '@/Components/crm/DisqualifyLeadModal.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'

const props = defineProps<{
  lead: {
    id: number
    name: string
    company_name: string | null
    source_id: number | null
    stage: string
    owner_id: number | null
    estimated_value: string | number | null
    next_action_at: string | null
    notes: string | null
    disqualify_reason: string | null
    converted_partner: { id: number; name: string; type: string } | null
    activities: LeadActivityRow[]
  }
  sources: Array<{ id: number; name: string }>
  owners: Array<{ id: number; name: string }>
  roleTypes: Array<{ id: number; name: string }>
  customFields: CustomFieldDef[]
}>()

const customBag: Record<string, string> = {}
for (const f of props.customFields) {
  customBag[f.code] = f.value ?? ''
}

const form = useForm({
  name: props.lead.name,
  company_name: props.lead.company_name ?? '',
  source_id: props.lead.source_id,
  owner_id: props.lead.owner_id,
  estimated_value: props.lead.estimated_value ?? '',
  next_action_at: props.lead.next_action_at ?? '',
  notes: props.lead.notes ?? '',
  custom_fields: customBag,
})

const submit = () => form.put(route('crm.leads.update', props.lead.id))

const isOpen = props.lead.stage !== 'converted' && props.lead.stage !== 'disqualified'
const showConvert = ref(false)
const showDisqualify = ref(false)

const convertedPartnerHref = () => {
  if (!props.lead.converted_partner) return '#'
  return props.lead.converted_partner.type === 'organization'
    ? route('crm.companies.edit', props.lead.converted_partner.id)
    : route('crm.contacts.edit', props.lead.converted_partner.id)
}
</script>

<template>
  <AppLayout>
    <PageHeader :title="lead.name" :description="lead.company_name ?? 'No company'">
      <template #actions>
        <StatusBadge :status="lead.stage" />
      </template>
    </PageHeader>

    <CrmSubNav active="leads" class="mt-6" />

    <div class="mt-6 grid max-w-4xl grid-cols-1 gap-6 lg:grid-cols-3">
      <Panel class="lg:col-span-2">
        <form class="space-y-4" @submit.prevent="submit">
          <FormInput v-model="form.name" name="name" label="Name" :error="form.errors.name" required />
          <FormInput v-model="form.company_name" name="company_name" label="Company" :error="form.errors.company_name" />
          <FormSelect
            v-model="form.source_id"
            name="source_id"
            label="Source"
            placeholder="Unknown"
            :options="sources.map((s) => ({ label: s.name, value: s.id }))"
            :error="form.errors.source_id"
          />
          <FormSelect
            v-model="form.owner_id"
            name="owner_id"
            label="Owner"
            placeholder="Unassigned"
            :options="owners.map((o) => ({ label: o.name, value: o.id }))"
            :error="form.errors.owner_id"
          />
          <FormInput
            v-model="form.estimated_value"
            name="estimated_value"
            type="number"
            label="Estimated value"
            :error="form.errors.estimated_value"
          />
          <FormInput
            v-model="form.next_action_at"
            name="next_action_at"
            type="datetime-local"
            label="Next action"
            :error="form.errors.next_action_at"
          />
          <div class="space-y-1.5">
            <label class="text-sm font-medium text-ink-900">Notes</label>
            <textarea
              v-model="form.notes"
              rows="3"
              class="w-full rounded-sm border border-border bg-surface-0 px-3 py-2 text-sm text-ink-900 shadow-sm focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"
            />
          </div>

          <CustomFieldInputs
            v-model="form.custom_fields"
            :fields="customFields"
            :errors="form.errors"
          />

          <div class="flex items-center justify-end gap-3 border-t border-border pt-4">
            <Link
              :href="route('crm.leads.index')"
              class="inline-flex items-center justify-center rounded-sm border border-border bg-surface-0 px-3 py-2 text-sm font-semibold text-ink-900 shadow-sm transition hover:bg-surface-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
            >
              Cancel
            </Link>
            <PrimaryButton type="submit" :disabled="form.processing">Update lead</PrimaryButton>
          </div>
        </form>
      </Panel>

      <div class="space-y-6">
        <Panel title="Pipeline">
          <div v-if="lead.converted_partner" class="text-sm">
            <p class="text-ink-600">Converted to:</p>
            <Link :href="convertedPartnerHref()" class="font-medium text-accent hover:underline">
              {{ lead.converted_partner.name }}
            </Link>
          </div>
          <div v-else-if="lead.stage === 'disqualified'" class="text-sm">
            <p class="text-ink-600">Disqualify reason:</p>
            <p class="font-medium text-ink-900">{{ lead.disqualify_reason }}</p>
          </div>
          <div v-else class="space-y-2">
            <button
              type="button"
              class="w-full rounded-md border border-signal-success/40 bg-signal-success/5 px-3 py-2 text-sm font-semibold text-signal-success hover:bg-signal-success/10"
              @click="showConvert = true"
            >
              Convert to Partner
            </button>
            <button
              type="button"
              class="w-full rounded-md border border-signal-danger/40 bg-signal-danger/5 px-3 py-2 text-sm font-semibold text-signal-danger hover:bg-signal-danger/10"
              @click="showDisqualify = true"
            >
              Disqualify
            </button>
          </div>
        </Panel>

        <Panel title="Activity">
          <LeadActivityLog :lead-id="lead.id" :activities="lead.activities" />
        </Panel>
      </div>
    </div>

    <ConvertLeadModal
      :show="showConvert"
      :lead-id="lead.id"
      :lead-name="lead.name"
      :has-company-name="!!lead.company_name"
      :role-types="roleTypes"
      @close="showConvert = false"
    />
    <DisqualifyLeadModal
      :show="showDisqualify"
      :lead-id="lead.id"
      :lead-name="lead.name"
      @close="showDisqualify = false"
    />
  </AppLayout>
</template>

// next-fe/src/app/inventory/[id]/edit/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import PageHeader from "@/components/layout/PageHeader";
import FormInput from "@/components/forms/FormInput";
import FormSelect from "@/components/forms/FormSelect";
import { getCategories, getItemById, saveItem, Category } from "@/lib/storage";

export default function EditItemPage() {
  const router = useRouter();
  const params = useParams();
  const id = params?.id ? Number(params.id) : null;

  const [categories, setCategories] = useState<Category[]>([]);
  const [notFound, setNotFound] = useState(false);

  // Form Fields State
  const [code, setCode] = useState("");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [stock, setStock] = useState("0");
  const [minimumStock, setMinimumStock] = useState("0");
  const [unit, setUnit] = useState("");
  const [status, setStatus] = useState("active");

  // Error States
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    setCategories(getCategories());

    if (id !== null && !isNaN(id)) {
      const item = getItemById(id);
      if (item) {
        setCode(item.code);
        setName(item.name);
        setDescription(item.description || "");
        setCategoryId(String(item.inventory_category_id));
        setStock(String(item.stock));
        setMinimumStock(String(item.minimum_stock));
        setUnit(item.unit);
        setStatus(item.status);
      } else {
        setNotFound(true);
      }
    } else {
      setNotFound(true);
    }
  }, [id]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrors({});

    // Validate
    const newErrors: Record<string, string> = {};
    if (!code.trim()) newErrors.code = "Item code is required.";
    if (!name.trim()) newErrors.name = "Item name is required.";
    if (!categoryId) newErrors.categoryId = "Category is required.";
    if (!unit.trim()) newErrors.unit = "Unit of measurement is required.";
    if (isNaN(Number(stock)) || Number(stock) < 0) {
      newErrors.stock = "Stock must be a positive number.";
    }
    if (isNaN(Number(minimumStock)) || Number(minimumStock) < 0) {
      newErrors.minimumStock = "Minimum stock must be a positive number.";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    setIsSubmitting(true);

    try {
      saveItem({
        id: id!,
        code: code.trim().toUpperCase(),
        name: name.trim(),
        description: description.trim(),
        inventory_category_id: Number(categoryId),
        stock: Number(stock),
        minimum_stock: Number(minimumStock),
        unit: unit.trim(),
        status: status as "active" | "inactive" | "archived",
      });

      router.push("/inventory");
    } catch (err) {
      console.error(err);
      setIsSubmitting(false);
    }
  };

  if (notFound) {
    return (
      <AppLayout>
        <div className="text-center py-16 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl space-y-4 shadow-sm">
          <p className="text-sm font-semibold text-slate-800 dark:text-slate-200">
            Inventory item not found.
          </p>
          <Link
            href="/inventory"
            className="inline-flex items-center rounded-xl bg-indigo-650 px-4 py-2 text-xs font-bold text-white shadow-md shadow-indigo-650/10 hover:bg-indigo-600 transition-colors"
          >
            Back to Inventory List
          </Link>
        </div>
      </AppLayout>
    );
  }

  const categoryOptions = categories.map((c) => ({
    label: c.name,
    value: c.id,
  }));

  return (
    <AppLayout>
      <PageHeader
        title="Edit Inventory Item"
        description="Update inventory details for stock item."
      />

      <div className="mt-6 max-w-2xl rounded-xl border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm">
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput
              name="code"
              label="Item Code"
              placeholder="e.g. RAW-001"
              value={code}
              onChange={setCode}
              error={errors.code}
              required
            />

            <FormInput
              name="name"
              label="Item Name"
              placeholder="e.g. Steel Plate"
              value={name}
              onChange={setName}
              error={errors.name}
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormSelect
              name="inventory_category_id"
              label="Category"
              placeholder="Select category"
              value={categoryId}
              onChange={setCategoryId}
              options={categoryOptions}
              error={errors.categoryId}
              required
            />

            <FormInput
              name="unit"
              label="Unit of Measurement"
              placeholder="e.g. pcs, box, kg"
              value={unit}
              onChange={setUnit}
              error={errors.unit}
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput
              name="stock"
              label="Current Stock"
              type="number"
              value={stock}
              onChange={setStock}
              error={errors.stock}
              required
            />

            <FormInput
              name="minimum_stock"
              label="Minimum Safety Stock"
              type="number"
              value={minimumStock}
              onChange={setMinimumStock}
              error={errors.minimumStock}
              required
            />
          </div>

          <FormSelect
            name="status"
            label="Status"
            placeholder="Select status"
            value={status}
            onChange={setStatus}
            options={[
              { label: "Active", value: "active" },
              { label: "Inactive", value: "inactive" },
              { label: "Archived", value: "archived" },
            ]}
            required
          />

          <div className="space-y-1.5">
            <label
              htmlFor="description"
              className="block text-xs font-semibold text-slate-700 dark:text-slate-350"
            >
              Description
            </label>
            <textarea
              id="description"
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Optional brief description..."
              className="w-full rounded-lg border border-slate-250 dark:border-slate-800 bg-white dark:bg-slate-900 px-3 py-2 text-xs shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 dark:text-slate-200"
            ></textarea>
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
            <Link
              href="/inventory"
              className="text-xs font-bold text-slate-750 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white px-3 py-2"
            >
              Cancel
            </Link>
            <button
              type="submit"
              disabled={isSubmitting}
              className="rounded-xl bg-indigo-650 px-4 py-2 text-xs font-bold text-white shadow-md shadow-indigo-650/10 hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-50 active:scale-[0.98] transition-all"
            >
              {isSubmitting ? "Saving..." : "Save Changes"}
            </button>
          </div>
        </form>
      </div>
    </AppLayout>
  );
}
